<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DummyProdukSeeder extends Seeder
{
    public function run(): void
    {
        $produks = [
            [
                'idProduk' => 'PRD001',
                'namaProduk' => 'iPhone 13 Pro Max 256GB',
                'jenisProduk' => 'Handphone',
                'harga_beli' => 15000000,
                'harga_jual' => 16500000,
                'stok' => 5,
                'merk' => 'Apple',
                'warna' => 'Sierra Blue',
                'imei_sn' => '35930310' . rand(1000000, 9999999),
                'kondisi' => 'Baru',
                'garansi' => '1 Tahun iBox',
                'provider' => null,
                'nominal_kuota' => null,
                'masa_aktif' => null,
                'biaya_admin' => 0,
                'tipe_layanan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idProduk' => 'PRD002',
                'namaProduk' => 'Samsung Galaxy S23 Ultra',
                'jenisProduk' => 'Handphone',
                'harga_beli' => 18000000,
                'harga_jual' => 19999000,
                'stok' => 3,
                'merk' => 'Samsung',
                'warna' => 'Phantom Black',
                'imei_sn' => '35930311' . rand(1000000, 9999999),
                'kondisi' => 'Baru',
                'garansi' => '1 Tahun SEIN',
                'provider' => null,
                'nominal_kuota' => null,
                'masa_aktif' => null,
                'biaya_admin' => 0,
                'tipe_layanan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idProduk' => 'PRD003',
                'namaProduk' => 'Voucher Telkomsel 14GB',
                'jenisProduk' => 'Voucher Internet',
                'harga_beli' => 38000,
                'harga_jual' => 45000,
                'stok' => 50,
                'merk' => 'Telkomsel',
                'warna' => null,
                'imei_sn' => null,
                'kondisi' => 'Baru',
                'garansi' => null,
                'provider' => 'Telkomsel',
                'nominal_kuota' => '14 GB',
                'masa_aktif' => 30,
                'biaya_admin' => 0,
                'tipe_layanan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idProduk' => 'PRD004',
                'namaProduk' => 'Pulsa Indosat 50rb',
                'jenisProduk' => 'Pulsa Reguler',
                'harga_beli' => 49500,
                'harga_jual' => 52000,
                'stok' => 999,
                'merk' => 'Indosat',
                'warna' => null,
                'imei_sn' => null,
                'kondisi' => 'Baru',
                'garansi' => null,
                'provider' => 'Indosat',
                'nominal_kuota' => null,
                'masa_aktif' => null,
                'biaya_admin' => 0,
                'tipe_layanan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idProduk' => 'PRD005',
                'namaProduk' => 'Charger Anker 20W',
                'jenisProduk' => 'Aksesoris',
                'harga_beli' => 120000,
                'harga_jual' => 150000,
                'stok' => 15,
                'merk' => 'Anker',
                'warna' => 'Putih',
                'imei_sn' => null,
                'kondisi' => 'Baru',
                'garansi' => '18 Bulan',
                'provider' => null,
                'nominal_kuota' => null,
                'masa_aktif' => null,
                'biaya_admin' => 0,
                'tipe_layanan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idProduk' => 'PRD006',
                'namaProduk' => 'Top Up',
                'jenisProduk' => 'Top Up E-Wallet',
                'harga_beli' => 100000,
                'harga_jual' => 102000,
                'stok' => 999,
                'merk' => 'DANA',
                'warna' => null,
                'imei_sn' => null,
                'kondisi' => 'Baru',
                'garansi' => null,
                'provider' => 'DANA',
                'nominal_kuota' => null,
                'masa_aktif' => null,
                'biaya_admin' => 2000,
                'tipe_layanan' => 'E-Wallet',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('produks')->insert($produks);
    }
}
